#ifndef FMODTHUNDERSTORMPLUGIN_PARAMETERINDEX_H
#define FMODTHUNDERSTORMPLUGIN_PARAMETERINDEX_H

namespace ThunderStorm::InterfaceAdapter {
    enum {
        PARAM_RAIN_INTENSITY = 0,
        PARAM_THUNDER_TRIGGER,
        PARAM_THUNDER_DISTANCE,
        PARAM_THUNDER_FREQ,
        PARAM_INDOOR_OUTDOOR,
        PARAM_RAIN_VOLUME,
        PARAM_THUNDER_VOLUME,
        
        PARAM_THUNDER_STRIKE,
        PARAM_THUNDER_RUMBLE,
        PARAM_THUNDER_GROWL,
        
        PARAM_L1_LEVEL,
        PARAM_L1_DENSITY,
        PARAM_L1_COLOR,
        PARAM_L1_VISCOSITY,
        PARAM_L1_MIN,
        PARAM_L1_MAX,
        PARAM_L1_LOCUT,
        PARAM_L1_HICUT,
        
        PARAM_L2_LEVEL,
        PARAM_L2_DENSITY,
        PARAM_L2_COLOR,
        PARAM_L2_VISCOSITY,
        PARAM_L2_MIN,
        PARAM_L2_MAX,
        PARAM_L2_LOCUT,
        PARAM_L2_HICUT,

        PARAM_RUMBLE_LEVEL,
        PARAM_RUMBLE_LOCUT,
        PARAM_RUMBLE_HICUT,
        
        PARAM_SHOWER_LEVEL,
        PARAM_SHOWER_LOCUT,
        PARAM_SHOWER_HICUT,
        
        NUM_PARAMETERS
    };
}

#endif // FMODTHUNDERSTORMPLUGIN_PARAMETERINDEX_H
